services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gregcustomers-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "GregCustomer@123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: